name: audio
description: SoundCloud Audio Player for Flutter.

version: 0.0.7+1

environment:
  sdk: ">=2.9.0-8.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.15.1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  flutter_bloc: ^4.0.0

dev_dependencies:
  build_runner: ^1.8.1
  built_value_generator: ^7.1.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/tunes.json
