name: audio
description: SoundCloud style audio player in Flutter.

version: 0.0.5+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.14.0
  built_collection: ^4.3.2
  built_value: ^7.0.8
  cupertino_icons: ^0.1.3
  flutter_bloc: ^3.2.0

dev_dependencies:
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/tunes.json
